### ISSUE TITLE
iOS 11 support

### ISSUE THREAD

**Issue by timonus** [TimOliver/TOStatusBarSimulator#1]
The status bar has been slightly changed in iOS 11 :)

**Comment by TimOliver** [comment]
Hey Tim! Good to hear from you again!

Hahaha I wasn't watching this repo so I didn't get an alert about this issue, but I was just about to come in and write the same thing. Thanks! XD

The status bar in iOS 11 seems to be fluctuating between beta versions. The Wi-Fi icon got made slightly bolder in a recent version.

Once iOS 11 goes gold, I'll update this thing for it. :)

**Comment by timonus** [comment]
Thanks!

**Comment by TimOliver** [comment]
Added in #3. HOPEFULLY Apple won't change it anymore before then, but if they do, it should now be trivial to update this library to match. :)

**Comment by timonus** [comment]
Nice! Thank you
